project_id = "xsvoeygciztxzztmfeap"

[functions.generate-meal-suggestions]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.chat-meal-advice]
verify_jwt = false

[functions.send-daily-meals]
verify_jwt = false