project_id = "xsvoeygciztxzztmfeap"

[functions.generate-meal-suggestions]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.chat-meal-advice]
verify_jwt = false

[functions.send-meal-email]
verify_jwt = false

[functions.swap-meal]
verify_jwt = false
